Repository sir-dunxalot/ember-tooltips, pull requests merged in 2018-09, with the labels that each got.

#264 Refactored css to avoid need for sass, postcss and autoprefixer
  addon/styles/addon.css
  addon/styles/addon.scss
  ember-cli-build.js
  index.js
  package.json
  tests/dummy/app/styles/_variables.css
  tests/dummy/app/styles/_variables.scss
  tests/dummy/app/styles/app.css
  tests/dummy/app/styles/components/_code.css
  tests/dummy/app/styles/components/_code.scss
  tests/dummy/app/styles/vendor/_html5bp.css
  tests/dummy/app/styles/vendor/_normalize.css
  vendor/highlight.pack.js
Labels: 2.x, enhancement

#234 Fixes #231 fix for cannot read property popper of undefined
  addon/components/ember-tooltip-base.js
Labels: 3.x

#266 Incorporate relevant 2.x changes into 3.x
  .eslintignore
  .eslintrc.js
  .gitignore
  .npmignore
  .travis.yml
  LICENSE.md
  README.md
  addon/components/ember-popover.js
  addon/components/ember-tooltip-base.js
  addon/styles/_mixins.scss
  addon/styles/addon.css
  addon/styles/addon.scss
  addon/templates/components/ember-tooltip-base.hbs
  bower.json
  config/ember-try.js
  config/environment.js
  config/release.js
  ember-cli-build.js
  index.js
  package.json
  test-support/helpers/ember-tooltips.js
  testem.js
  tests/.eslintrc.js
  tests/acceptance/acceptance-test.js
  tests/acceptance/application-test.js
  tests/dummy/app/app.js
  tests/dummy/app/components/some-component.js
  tests/dummy/app/components/some-spinner.js
  tests/dummy/app/controllers/index.js
  tests/dummy/app/index.html
  tests/dummy/app/router.js
  tests/dummy/app/routes/application.js
  tests/dummy/app/styles/_variables.css
  tests/dummy/app/styles/_variables.scss
  tests/dummy/app/styles/app.css
  tests/dummy/app/styles/components/_code.css
  tests/dummy/app/styles/components/_code.scss
  tests/dummy/app/styles/vendor/_html5bp.css
  tests/dummy/app/styles/vendor/_normalize.css
  tests/dummy/app/templates/index.hbs
  tests/dummy/config/environment.js
  tests/dummy/config/targets.js
  tests/dummy/public/crossdomain.xml
  tests/helpers/.gitkeep
  tests/helpers/destroy-app.js
  tests/helpers/module-for-acceptance.js
  tests/helpers/resolver.js
  tests/helpers/start-app.js
  tests/integration/components/actions-test.js
  tests/integration/components/delay-test.js
  tests/integration/components/duration-test.js
  tests/integration/components/popover/api-test.js
  tests/integration/components/popover/click-test.js
  tests/integration/components/popover/event-bubbling-test.js
  vendor/highlight.pack.js
Labels: 3.x

#267 fix: run handlers within the runloop
  addon/components/lazy-render-wrapper.js
  addon/components/tether-popover-on-element.js
  addon/components/tether-tooltip-and-popover.js
  addon/components/tether-tooltip-on-element.js
Labels: 2.x

#265 Fix for glimmer 2 issue
  addon/components/lazy-render-wrapper.js
  addon/components/tether-tooltip-and-popover.js
  addon/templates/components/lazy-render-wrapper.hbs
  tests/integration/components/unstable-root-test.js
Labels: 2.x

#245 Positioning Issue with 3.0.0-beta.2
  addon/components/ember-tooltip-base.js
Labels: 3.x

#268 Prevent layout thrashing in popper onUpdate hook
  addon/components/ember-tooltip-base.js
Labels: 3.x

#274 Avoid creating additional runloops while destroying tooltips
  addon/components/ember-tooltip-base.js
  tests/acceptance/many-tooltips-test.js
  tests/dummy/app/router.js
  tests/dummy/app/routes/many-tooltips.js
  tests/dummy/app/templates/many-tooltips.hbs
Labels: 3.x

#276 Fix bug where bound text could not be updated
  addon/components/ember-tooltip-base.js
  addon/templates/components/ember-tooltip-base.hbs
  package-lock.json
  package.json
  tests/integration/components/side-test.js
  tests/integration/components/text-test.js
Labels: 3.x
